name: python-ml
dependencies:
  - python=3.6
  - seaborn=0.9
  - numpy=1.14.2
  - scipy=1.1
  - scikit-learn
  - ipython=7
  - jupyter=1.0.0
  - matplotlib=3.0.2
  - pandas 0.23.4
  - pillow
  - graphviz=2.38.0
  - python-graphviz=0.8.4